# Generated by Django 5.1 on 2024-09-05 19:32

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("employee", "Employee"),
                    ("customer", "Customer"),
                ],
                max_length=10,
            ),
        ),
    ]
